basicapp/urls.py
from django.urls import re_path as url
from basicapp import views

app_name ='basicapp'

urlpatterns = [

    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),

]

basicforms/urls.py
from django.urls import re_path as url
from django.urls import path , include
from django.contrib import admin
from basicapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    url(r'^basicapp',include('basicapp.urls')),
    url(r'^logout/$', views.user_logout,name='logout'),
    url(r'^special/',views.special,name='special')
    # url(r'^form_page/',views.form_name_view,name='form_name')
]



























# from django.contrib import admin
# from django.urls import path

# urlpatterns = [
#     path('admin/', admin.site.urls),
# ]

basicapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)

    #Additional classes
    portfolio_site = models.URLField(blank=True)

    profile_pic = models.ImageField(
        upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

basicapp/forms.py
from django import forms
from django.contrib.auth.models import User
from basicapp.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(
        widget=forms.PasswordInput())
    
    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')


        

    

basicapp/views.py
from django.shortcuts import render
from basicapp.forms import UserForm, UserProfileInfoForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout



# Create your views here.
def index(request):
    return render(request,'basicapp/index.html')

@login_required
def special(request):
    return HttpResponse("you are logged in, congratulations!")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True

        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm

    return render(request,'basicapp/registration.html',{'user_form':user_form,
                                                        'profile_form':profile_form,
                                                        'registered':registered}) 


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("ACCOUNT IS NOT IN ACTIVE STATE")
        else:
            print("some person tried to login and failed!")
            print("username:{} and password {}".format(username,password))
            return HttpResponse("invalid login details given!")
    else:
        return render(request,'basicapp/login.html',{})

templates/basicapp/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
        integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

    <title>user registration</title>
</head>

<body style="background-color: rgb(66, 170, 75);">
    <nav class="navbar navbar-expand-lg navbar-light bg-light" >
        <div class="container" style="background-color: rgb(226, 147, 43); max-width:100%; height: 2cm ;">
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'index' %}">Niralee</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'basicapp:register' %}">Register</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li><a class="nav-link" href="{% url 'logout' %}">LOGOUT</a></li>
                    {% else %}
                    <li><a class="nav-link" href="{% url 'basicapp:user_login' %}">LOGIN</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        {% block body_block %}
        {% endblock %}
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct"
        crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
    -->
</body>

</html>

templates/basicapp/index.html
{% extends "basicapp/base.html" %}
{% block body_block %}

<div class="jumbotron">
    <h1 class="display-4">Welcome to Niralee Technologies Pvt Ltd!</h1>
    <p class="lead"> Niralee Technologies Pvt Ltd is a software Development Company Which develops Software products</p>
    <hr class="my-4">
    <p>We also provide internship that can provide unique oppotunities for learning outside of academic settings.</p>
    <a class="btn btn-primary btn-lg" href="https://www.niraleetechnologies.com/" role="button">niralee</a>
  </div>

{% endblock %}

templates/basicapp/login.html
{% extends "basicapp/base.html" %}
{% block body_block %}

<div class="jumbotron">



    <h1>Please Login To Continue </h1>
    <br>
    <hr>
    <form action="{% url 'basicapp:user_login' %}" method="post">
        {% csrf_token %}
        <label for="username">username:</label>
        <input type="text" name="username" placeholder="Enter Username Here">

        <label for="password">password:</label>
        <input type="password" name="password">

        <input type="submit" value="LOGIN" name="">

    </form>
    
</div>

 

{% endblock %}


















<!-- <form enctype="multipart/form-data" method="post">
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    <input type="submit" value="Register" name="">
 </form> -->

templates/basicapp/registration.html
{% extends "basicapp/base.html" %}
{% load static %}
{% block body_block %}

<div class="jumbotron">
{% if registered %}
<h1>Thank You for Registering!</h1>

{% else %}
<h1>You can register here!</h1>
<br>
<h3>Please Fill Out The Form Below</h3>
    <br>
    <hr>
    <form enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <input type="submit" value="Register" name="">
     </form>
     {% endif %}
</div>

 
{% endblock %}